// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXVvYz3ljZWF4NCk_2wFCMBsEfLBdg1w',
    appId: '1:15915064363:web:affee488454a62d5fbde6e',
    messagingSenderId: '15915064363',
    projectId: 'tag-ok',
    authDomain: 'tag-ok.firebaseapp.com',
    storageBucket: 'tag-ok.firebasestorage.app',
    measurementId: 'G-22KGS61ZSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsyqri092PaalQsF3C2znyTmNOCh5RJ0',
    appId: '1:15915064363:android:26d558fe82f5916cfbde6e',
    messagingSenderId: '15915064363',
    projectId: 'tag-ok',
    storageBucket: 'tag-ok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq-6pdAcH8gAkOEYOp4HzcX5AC1yqIzyk',
    appId: '1:15915064363:ios:a86d4c4a9564d813fbde6e',
    messagingSenderId: '15915064363',
    projectId: 'tag-ok',
    storageBucket: 'tag-ok.firebasestorage.app',
    iosBundleId: 'com.example.tagOk',
  );

}